name: Blokus Gym Environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    strategy:
      matrix:
        python-version: [3.7]
        runs-on: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v1
    - name: Cache on ${{ matrix.runs-on }}
      if: runner.os == 'Linux'
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
    - name: Cache on ${{ matrix.runs-on }}
      if: runner.os == 'Windows'
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint autopep8 mypy

    - name: PyLint
      shell: pwsh
      run: |
        Get-ChildItem "blokus/**/*.py" -Recurse | ForEach-Object { 
          pylint -s n $_
          if (!$?) {
            throw "something went wrong"
          }
        }
    # - name: PyLint
    #   shell: bash
    #   run: |
    #     cd blokus && find . -type f -name "*.py" | xargs pylint -s n && exit 1

    # - name: AutoPep8 on ${{ matrix.runs-on }}
    #   if: runner.os == 'Windows'
    #   run: |
    #     $changes=(autopep8 --recursive --diff --aggressive blokus); if($changes -ne $null) { Write-Host $changes; exit 1 }
    # - name: AutoPep8 on ${{ matrix.runs-on }}
    #   if: runner.os == 'Linux'
    #   run: |
    #     changes=$(autopep8 --recursive --diff --aggressive blokus); if [[ $changes ]]; then echo "$changes" && exit 1; fi

    # - name: Mypy
    #   run: |
    #     mypy --config-file=mypy.ini blokus
