name: Blokus Gym Environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: pwsh

jobs:
  lint:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        runs-on: [ubuntu-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v1
      if: runner.os == 'Linux'
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
      if: runner.os == 'Windows'
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint autopep8 mypy

    - name: PyLint
      run: |
        pylint blokus

    - name: AutoPep8
      run: |
        $changes = autopep8 --recursive --diff --aggressive blokus
        if($changes -ne $null) {
          throw $changes
        }

