name: Blokus application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        runs-on: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python Matrix ${{ matrix.python-version }} on ${{ matrix.runs-on }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "requirements.txt"
        pip install pylint
    - name: Lint with pylint on ${{ matrix.runs-on }}
      if: runner.os == 'Windows'
      run: |
        Get-ChildItem "blokus/**/*.py" -Recurse | ForEach-Object { pylint -s n $_ }
    - name: Lint with pylint on ${{ matrix.runs-on }}
      if: runner.os == 'Linux'
      run: |
        cd blokus && find . -type f -name "*.py" | xargs python3 -m pylint -s n
